#####################################################################
# trailing newline
# Expect all to be updated
# result - last FROM ignored, alias missing from first FROM
#####################################################################
FROM debian:wheezy  as stage-1

#####################################################################
FROM debian:wheezy  as stage-2

#####################################################################
FROM debian:wheezy@sha256:d00f167f8f2e70ecc2e0f5410a3cb74cd4ad720e33b9810da6a2dcfa81dccfc0

