#####################################################################
# trailing newline
# Expect all to be updated
# result - last FROM ignored, alias missing from first FROM
#####################################################################
FROM debian:wheezy  as stage-1

#####################################################################
FROM debian:wheezy  as stage-2

#####################################################################
FROM debian:wheezy@sha256:37103c15605251b2e35b70a3214af626a55cff39abbaadccd01ff828ee7005e0

