#####################################################################
# trailing newline
# Expect all to be updated
# result - last FROM ignored, alias missing from first FROM
#####################################################################
FROM debian:wheezy  as stage-1

#####################################################################
FROM debian:wheezy  as stage-2

#####################################################################
FROM debian:wheezy@sha256:a69871c0696dcc995ea3d4a2d5c849b22f1ca1f1d13a3049b689ff2af6e95842

