#####################################################################
# more than 3 FROM statements
# Expect all to be updated
# result - last FROM ignored
#####################################################################
FROM node:alpine@sha256:565dfb5f10143efd5f4c9df75a63d765adcd14b150fc61e5c1d54d70cb006e86 as stage-1

#####################################################################
FROM node:alpine@sha256:565dfb5f10143efd5f4c9df75a63d765adcd14b150fc61e5c1d54d70cb006e86 as stage-2

#####################################################################
FROM node:alpine@sha256:565dfb5f10143efd5f4c9df75a63d765adcd14b150fc61e5c1d54d70cb006e86 as stage-3

#####################################################################
FROM node:alpine@sha256:565dfb5f10143efd5f4c9df75a63d765adcd14b150fc61e5c1d54d70cb006e86
