#####################################################################
# trailing new line, matching FROM
# EXPECT all three aliases to be un-changed
# RESULT - digest added, no changes to aliass
#####################################################################
FROM debian:wheezy as stage-1

#####################################################################
FROM node:alpine as stage-2

#####################################################################
FROM node:alpine as stage-3
