#####################################################################
# less than 3 FROM statements
# Expect all to be updated
# result - last FROM ignored
#####################################################################
FROM node:alpine@sha256:d3780f5d4e49743e448f037c75b533123c3f96eb51750fc83c3e59b791a1cabf as stage-1

#####################################################################
FROM node:alpine@sha256:d3780f5d4e49743e448f037c75b533123c3f96eb51750fc83c3e59b791a1cabf
