#####################################################################
# less than 3 FROM statements
# Expect all to be updated
# result - last FROM ignored
#####################################################################
FROM node:alpine@sha256:7965557edee8e5c8c1b03c71387a49bddc6dbed580bb77caf7ef16690b5aee78 as stage-1

#####################################################################
FROM node:alpine@sha256:7965557edee8e5c8c1b03c71387a49bddc6dbed580bb77caf7ef16690b5aee78
