#####################################################################
# no trailing newline
# Expect all to be updated
# result - last FROM ignored
#####################################################################
FROM debian:wheezy@sha256:37103c15605251b2e35b70a3214af626a55cff39abbaadccd01ff828ee7005e0 as stage-1

#####################################################################
FROM node:alpine@sha256:1b79097c21e5b01ad871c2c6684da5278b302b49201b747836757446cd095cd4 as stage-2

#####################################################################
FROM debian:wheezy@sha256:37103c15605251b2e35b70a3214af626a55cff39abbaadccd01ff828ee7005e0
